# Generated by Django 4.0.4 on 2022-11-18 10:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=10)),
                ('to_name', models.CharField(max_length=10)),
                ('sender', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('sendAt', models.DateTimeField(default=datetime.datetime(2022, 11, 18, 1, 53, 13, 223843, tzinfo=utc))),
                ('openAt', models.DateTimeField(default=datetime.datetime(2023, 11, 17, 15, 0, 0, 223843, tzinfo=utc))),
                ('isOpened', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
