# Generated by Django 4.0.4 on 2022-11-18 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='openAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 15, 0, 0, 542271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sendAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 1, 55, 59, 542271, tzinfo=utc)),
        ),
    ]
