# Generated by Django 4.1.3 on 2022-11-24 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_alter_letter_openat_alter_letter_sendat'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='openAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 15, 0, 0, 635630, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sendAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 2, 21, 55, 635630, tzinfo=datetime.timezone.utc)),
        ),
    ]
