# Generated by Django 4.1.3 on 2022-11-29 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_letter_image_alter_letter_openat_alter_letter_sendat'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='dday',
            field=models.PositiveSmallIntegerField(default=365),
        ),
        migrations.AlterField(
            model_name='letter',
            name='openAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 0, 0, 968436, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sendAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 11, 13, 46, 968436, tzinfo=datetime.timezone.utc)),
        ),
    ]
